# Generated by Django 5.0.1 on 2025-06-20 20:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsencePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.CharField(max_length=200, verbose_name='Motif')),
                ('is_justified', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('justification_document', models.FileField(blank=True, null=True, upload_to='absence_periods/%Y/%m/', verbose_name='Justificatif')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Notifié le')),
            ],
            options={
                'verbose_name': "Période d'absence",
                'verbose_name_plural': "Périodes d'absence",
                'db_table': 'absence_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('excused', 'Absent excusé'), ('excluded', 'Exclu')], default='present', max_length=20, verbose_name='Statut')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes de retard')),
                ('is_justified', models.BooleanField(default=False, verbose_name='Justifié')),
                ('justification_document', models.FileField(blank=True, null=True, upload_to='justifications/%Y/%m/', verbose_name='Document justificatif')),
                ('justification_reason', models.TextField(blank=True, verbose_name='Motif')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'attendances',
                'ordering': ['-date', 'schedule__time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('absence_count', "Nombre d'absences"), ('late_count', 'Nombre de retards'), ('consecutive_absence', 'Absences consécutives'), ('pattern', 'Schéma récurrent')], max_length=30, verbose_name="Type d'alerte")),
                ('threshold_value', models.IntegerField(verbose_name='Valeur seuil atteinte')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('message', models.TextField(verbose_name="Message d'alerte")),
                ('details', models.JSONField(default=dict, verbose_name='Détails supplémentaires')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
            ],
            options={
                'verbose_name': "Alerte d'assiduité",
                'verbose_name_plural': "Alertes d'assiduité",
                'db_table': 'attendance_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sanction_type', models.CharField(choices=[('warning', 'Avertissement'), ('blame', 'Blâme'), ('detention', 'Retenue'), ('exclusion_temp', 'Exclusion temporaire'), ('exclusion_def', 'Exclusion définitive'), ('work', 'Travail supplémentaire'), ('community_service', "Travail d'intérêt général")], max_length=30, verbose_name='Type de sanction')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la sanction')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('detention_date', models.DateField(blank=True, null=True, verbose_name='Date de la retenue')),
                ('detention_start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('detention_end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('detention_room', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('exclusion_start_date', models.DateField(blank=True, null=True, verbose_name="Début d'exclusion")),
                ('exclusion_end_date', models.DateField(blank=True, null=True, verbose_name="Fin d'exclusion")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Effectuée')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Notes de suivi')),
                ('parents_notified', models.BooleanField(default=False, verbose_name='Parents notifiés')),
                ('notification_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'db_table': 'sanctions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('behavior_type', models.CharField(choices=[('positive', 'Positif'), ('negative', 'Négatif'), ('neutral', 'Neutre')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(help_text='Ex: Participation, Respect, Travail, etc.', max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('points', models.IntegerField(default=0, help_text='Positif ou négatif selon le comportement', verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Comportement',
                'verbose_name_plural': 'Comportements',
                'db_table': 'student_behaviors',
                'ordering': ['-date'],
            },
        ),
    ]
