# Generated by Django 5.0.1 on 2025-06-20 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceperiod',
            name='notified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_absences', to=settings.AUTH_USER_MODEL, verbose_name='Notifié par'),
        ),
        migrations.AddField(
            model_name='absenceperiod',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='timetable.schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='notified_users',
            field=models.ManyToManyField(related_name='received_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs notifiés'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanction',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_sanctions', to=settings.AUTH_USER_MODEL, verbose_name='Donnée par'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbehavior',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_behaviors', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='studentbehavior',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendances_date_684e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendances_student_1e9785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['student', 'is_resolved'], name='attendance__student_92cc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['alert_type', 'created_at'], name='attendance__alert_t_660b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['student', 'date'], name='sanctions_student_80e305_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['sanction_type', 'is_completed'], name='sanctions_sanctio_a2e12d_idx'),
        ),
    ]
